"""Manage timezones."""

import logging
from datetime import datetime
from os import environ

import pytz

# Replace pytz with dateutil
# https://assert.cc/posts/dateutil-preferred/

logging.basicConfig(level=environ.get("LOG_LEVEL", logging.INFO))
logging.getLogger(__name__)


def convert_time_to_utc(time, timezone):
    """Converts time to UTC."""
    logging.debug("Converting '%s' to UTC", timezone)
    event_time = {}
    for field in time:
        if "Z" not in time[field]:
            _timezone = standardize_timezone_name(timezone)
            event_time[field] = convert_to_utc(
                time=time[field], timezone=_timezone
            )

    return event_time


def standardize_timezone_name(timezone):
    """Converts timezone names to accepted standard for pytz."""
    logging.debug("Converting '%s' to accepted format", timezone)

    timezones = {
        "AUS Central Standard Time": "Australia/Darwin",
        "AUS Eastern Standard Time": "Australia/Sydney",
        "Abu Dhabi, Muscat": "Asia/Dubai",
        "Adelaide": "Australia/Adelaide",
        "Afghanistan Standard Time": "Asia/Kabul",
        "Alaska": "America/Anchorage",
        "Alaskan Standard Time": "America/Anchorage",
        "Aleutian Standard Time": "America/Adak",
        "Altai Standard Time": "Asia/Barnaul",
        "Amman": "Asia/Amman",
        "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna": "Europe/Berlin",
        "Anadyr, Petropavlovsk-Kamchatsky (RTZ 11)": "Asia/Kamchatka",
        "Arab Standard Time": "Asia/Riyadh",
        "Arabian Standard Time": "Asia/Dubai",
        "Arabic Standard Time": "Asia/Baghdad",
        "Argentina Standard Time": "America/Buenos_Aires",
        "Arizona": "America/Phoenix",
        "Ashgabat, Tashkent": "Asia/Tashkent",
        "Astana": "Asia/Almaty",
        "Astrakhan Standard Time": "Europe/Astrakhan",
        "Asuncion": "America/Asuncion",
        "Athens, Bucharest": "Europe/Bucharest",
        "Atlantic Standard Time": "America/Halifax",
        "Atlantic Time (Canada)": "America/Halifax",
        "Auckland, Wellington": "Pacific/Auckland",
        "Aus Central W. Standard Time": "Australia/Eucla",
        "Azerbaijan Standard Time": "Asia/Baku",
        "Azores Standard Time": "Atlantic/Azores",
        "Azores": "Atlantic/Azores",
        "Baghdad": "Asia/Baghdad",
        "Bahia Standard Time": "America/Bahia",
        "Baja California": "America/Tijuana",
        "Baku": "Asia/Baku",
        "Bangkok, Hanoi, Jakarta": "Asia/Bangkok",
        "Bangladesh Standard Time": "Asia/Dhaka",
        "Beijing, Chongqing, Hong Kong, Urumqi": "Asia/Shanghai",
        "Beirut": "Asia/Beirut",
        "Belarus Standard Time": "Europe/Minsk",
        "Belgrade, Bratislava, Budapest, Ljubljana, Prague": "Europe/Budapest",
        "Bogota, Lima, Quito, Rio Branco": "America/Bogota",
        "Bougainville Standard Time": "Pacific/Bougainville",
        "Brasilia": "America/Sao_Paulo",
        "Brisbane": "Australia/Brisbane",
        "Brussels, Copenhagen, Madrid, Paris": "Europe/Paris",
        "Cabo Verde Is.": "Atlantic/Cape_Verde",
        "Cairo": "Africa/Cairo",
        "Canada Central Standard Time": "America/Regina",
        "Canberra, Melbourne, Sydney": "Australia/Brisbane",
        "Cape Verde Standard Time": "Atlantic/Cape_Verde",
        "Caracas": "America/Caracas",
        "Casablanca": "Africa/Casablanca",
        "Caucasus Standard Time": "Asia/Yerevan",
        "Cayenne, Fortaleza": "America/Cayenne",
        "Cen. Australia Standard Time": "Australia/Adelaide",
        "Central America Standard Time": "America/Guatemala",
        "Central America": "America/Chicago",
        "Central Asia Standard Time": "Asia/Almaty",
        "Central Brazilian Standard Time": "America/Cuiaba",
        "Central Europe Standard Time": "Europe/Budapest",
        "Central European Standard Time": "Europe/Warsaw",
        "Central Pacific Standard Time": "Pacific/Guadalcanal",
        "Central Standard Time (Mexico)": "America/Mexico_City",
        "Central Standard Time": "America/Chicago",
        "Central Time (US & Canada)": "America/Chicago",
        "Chatham Islands Standard Time": "Pacific/Chatham",
        "Chennai, Kolkata, Mumbai, New Delhi": "Asia/Calcutta",
        "Chetumal": "America/Cancun",
        "Chihuahua, La Paz, Mazatlan": "America/Chihuahua",
        "China Standard Time": "Asia/Shanghai",
        "Chokurdakh (RTZ 10)": "Asia/Srednekolymsk",
        "City of Buenos Aires": "America/Buenos_Aires",
        "Coordinated Universal Time": "Etc/GMT",
        "Coordinated Universal Time+12": "Etc/GMT-12",
        "Coordinated Universal Time-02": "Etc/GMT+2",
        "Coordinated Universal Time-11": "Etc/GMT+11",
        "Cuba Standard Time": "America/Havana",
        "Cuiaba": "America/Cuiaba",
        "Damascus": "Asia/Damascus",
        "Darwin": "Australia/Darwin",
        "Dateline Standard Time": "Etc/GMT+12",
        "Dhaka": "Asia/Dhaka",
        "Dublin, Edinburgh, Lisbon, London": "Europe/London",
        "E. Africa Standard Time": "Africa/Nairobi",
        "E. Australia Standard Time": "Australia/Brisbane",
        "E. Europe Standard Time": "Europe/Chisinau",
        "E. Europe": "Europe/Chisinau",
        "E. South America Standard Time": "America/Sao_Paulo",
        "Easter Island Standard Time": "Pacific/Easter",
        "Eastern Standard Time (Mexico)": "America/Cancun",
        "Eastern Standard Time": "America/New_York",
        "Eastern Time (US & Canada)": "America/New_York",
        "Egypt Standard Time": "Africa/Cairo",
        "Ekaterinburg (RTZ 4)": "Asia/Yekaterinburg",
        "Ekaterinburg Standard Time": "Asia/Yekaterinburg",
        "FLE Standard Time": "Europe/Kiev",
        "Fiji Standard Time": "Pacific/Fiji",
        "Fiji": "Pacific/Fiji",
        "GMT Standard Time": "Europe/London",
        "GTB Standard Time": "Europe/Bucharest",
        "Georgetown, La Paz, Manaus, San Juan": "America/La_Paz",
        "Georgian Standard Time": "Asia/Tbilisi",
        "Greenland Standard Time": "America/Godthab",
        "Greenland": "America/Godthab",
        "Greenwich Standard Time": "Atlantic/Reykjavik",
        "Guadalajara, Mexico City, Monterrey": "America/Mexico_City",
        "Guam, Port Moresby": "Pacific/Port_Moresby",
        "Haiti Standard Time": "America/Port-au-Prince",
        "Harare, Pretoria": "Africa/Johannesburg",
        "Hawaii": "Pacific/Honolulu",
        "Hawaiian Standard Time": "Pacific/Honolulu",
        "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius": "Europe/Kiev",
        "Hobart": "Australia/Hobart",
        "India Standard Time": "Asia/Calcutta",
        "Indiana (East)": "America/Indianapolis",
        "International Date Line West": "Etc/GMT+12",
        "Iran Standard Time": "Asia/Tehran",
        "Irkutsk (RTZ 7)": "Asia/Irkutsk",
        "Islamabad, Karachi": "Asia/Karachi",
        "Israel Standard Time": "Asia/Jerusalem",
        "Istanbul": "Europe/Istanbul",
        "Izhevsk, Samara (RTZ 3)": "Europe/Samara",
        "Jerusalem": "Asia/Jerusalem",
        "Jordan Standard Time": "Asia/Amman",
        "Kabul": "Asia/Kabul",
        "Kaliningrad (RTZ 1)": "Europe/Kaliningrad",
        "Kaliningrad Standard Time": "Europe/Kaliningrad",
        "Kathmandu": "Asia/Katmandu",
        "Kiritimati Island": "Pacific/Kiritimati",
        "Korea Standard Time": "Asia/Seoul",
        "Krasnoyarsk (RTZ 6)": "Asia/Irkutsk",
        "Kuala Lumpur, Singapore": "Asia/Singapore",
        "Kuwait, Riyadh": "Asia/Riyadh",
        "Libya Standard Time": "Africa/Tripoli",
        "Line Islands Standard Time": "Pacific/Kiritimati",
        "Lord Howe Standard Time": "Australia/Lord_Howe",
        "Magadan Standard Time": "Asia/Magadan",
        "Magadan": "Asia/Magadan",
        "Magallanes Standard Time": "America/Punta_Arenas",
        "Marquesas Standard Time": "Pacific/Marquesas",
        "Mauritius Standard Time": "Indian/Mauritius",
        "Middle East Standard Time": "Asia/Beirut",
        "Minsk": "Europe/Minsk",
        "Monrovia, Reykjavik": "Atlantic/Reykjavik",
        "Montevideo Standard Time": "America/Montevideo",
        "Montevideo": "America/Montevideo",
        "Morocco Standard Time": "Africa/Casablanca",
        "Moscow, St. Petersburg, Volgograd (RTZ 2)": "Europe/Moscow",
        "Mountain Standard Time (Mexico)": "America/Chihuahua",
        "Mountain Standard Time": "America/Denver",
        "Mountain Time (US & Canada)": "America/Denver",
        "Myanmar Standard Time": "Asia/Rangoon",
        "N. Central Asia Standard Time": "Asia/Novosibirsk",
        "Nairobi": "Africa/Nairobi",
        "Namibia Standard Time": "Africa/Windhoek",
        "Nepal Standard Time": "Asia/Katmandu",
        "New Zealand Standard Time": "Pacific/Auckland",
        "Newfoundland Standard Time": "America/St_Johns",
        "Newfoundland": "America/St_Johns",
        "Norfolk Standard Time": "Pacific/Norfolk",
        "North Asia East Standard Time": "Asia/Irkutsk",
        "North Asia Standard Time": "Asia/Krasnoyarsk",
        "North Korea Standard Time": "Asia/Pyongyang",
        "Novosibirsk (RTZ 5)": "Asia/Novosibirsk",
        "Nuku’alofa": "Pacific/Tongatapu",
        "Omsk Standard Time": "Asia/Omsk",
        "Osaka, Sapporo, Tokyo": "Asia/Tokyo",
        "Pacific SA Standard Time": "America/Santiago",
        "Pacific Standard Time (Mexico)": "America/Tijuana",
        "Pacific Standard Time": "America/Los_Angeles",
        "Pacific Time (US & Canada)": "America/Los_Angeles",
        "Pakistan Standard Time": "Asia/Karachi",
        "Paraguay Standard Time": "America/Asuncion",
        "Perth": "Australia/Perth",
        "Port Louis": "Indian/Mauritius",
        "Romance Standard Time": "Europe/Paris",
        "Russia Time Zone 10": "Asia/Srednekolymsk",
        "Russia Time Zone 11": "Asia/Kamchatka",
        "Russia Time Zone 3": "Europe/Samara",
        "Russian Standard Time": "Europe/Moscow",
        "SA Eastern Standard Time": "America/Cayenne",
        "SA Pacific Standard Time": "America/Bogota",
        "SA Western Standard Time": "America/La_Paz",
        "SE Asia Standard Time": "Asia/Bangkok",
        "Saint Pierre Standard Time": "America/Miquelon",
        "Sakhalin Standard Time": "Asia/Sakhalin",
        "Salvador": "America/Bahia",
        "Samoa Standard Time": "Pacific/Apia",
        "Samoa": "Pacific/Apia",
        "Santiago": "America/Santiago",
        "Sao Tome Standard Time": "Africa/Sao_Tome",
        "Sarajevo, Skopje, Warsaw, Zagreb": "Europe/Warsaw",
        "Saratov Standard Time": "Europe/Saratov",
        "Saskatchewan": "America/Regina",
        "Seoul": "Asia/Seoul",
        "Singapore Standard Time": "Asia/Singapore",
        "Solomon Is., New Caledonia": "Pacific/Guadalcanal",
        "South Africa Standard Time": "Africa/Johannesburg",
        "Sri Jayawardenepura": "Asia/Colombo",
        "Sri Lanka Standard Time": "Asia/Colombo",
        "Sudan Standard Time": "Africa/Khartoum",
        "Syria Standard Time": "Asia/Damascus",
        "Taipei Standard Time": "Asia/Taipei",
        "Taipei": "Asia/Taipei",
        "Tasmania Standard Time": "Australia/Hobart",
        "Tbilisi": "Asia/Tbilisi",
        "Tehran": "Asia/Tehran",
        "Tocantins Standard Time": "America/Araguaina",
        "Tokyo Standard Time": "Asia/Tokyo",
        "Tomsk Standard Time": "Asia/Tomsk",
        "Tonga Standard Time": "Pacific/Tongatapu",
        "Transbaikal Standard Time": "Asia/Chita",
        "Tripoli": "Africa/Tripoli",
        "Turkey Standard Time": "Europe/Istanbul",
        "Turks And Caicos Standard Time": "America/Grand_Turk",
        "US Eastern Standard Time": "America/Indianapolis",
        "US Mountain Standard Time": "America/Phoenix",
        "UTC": "Etc/GMT",
        "UTC+12": "Etc/GMT-12",
        "UTC+13": "Etc/GMT-13",
        "UTC-02": "Etc/GMT+2",
        "UTC-08": "Etc/GMT+8",
        "UTC-09": "Etc/GMT+9",
        "UTC-11": "Etc/GMT+11",
        "Ulaanbaatar Standard Time": "Asia/Ulaanbaatar",
        "Ulaanbaatar": "Asia/Ulaanbaatar",
        "Venezuela Standard Time": "America/Caracas",
        "Vladivostok Standard Time": "Asia/Vladivostok",
        "Vladivostok, Magadan (RTZ 9)": "Asia/Vladivostok",
        "W. Australia Standard Time": "Australia/Perth",
        "W. Central Africa Standard Time": "Africa/Lagos",
        "W. Europe Standard Time": "Europe/Berlin",
        "W. Mongolia Standard Time": "Asia/Hovd",
        "West Asia Standard Time": "Asia/Tashkent",
        "West Bank Standard Time": "Asia/Hebron",
        "West Central Africa": "Africa/Lagos",
        "West Pacific Standard Time": "Pacific/Port_Moresby",
        "Windhoek": "Africa/Windhoek",
        "Yakutsk (RTZ 8)": "Asia/Yakutsk",
        "Yakutsk Standard Time": "Asia/Yakutsk",
        "Yangon (Rangoon)": "Asia/Rangoon",
        "Yerevan": "Asia/Yerevan",
    }

    return timezones.get(timezone, timezone)


def convert_to_utc(time, timezone):
    """Converts time to UTC."""
    logging.debug("Converting to UTC")
    _time = datetime.strptime(time, "%Y%m%dT%H%M%S")
    _timezone = pytz.timezone(timezone)
    utc_time = _timezone.localize(_time, is_dst=True).astimezone(pytz.utc)

    return utc_time.strftime("%Y%m%dT%H%M%SZ")
