build-SharedLib:
	mkdir -p "$(ARTIFACTS_DIR)/python"
	cp conftest.py "$(ARTIFACTS_DIR)/python"
	cp -r thirtyone "$(ARTIFACTS_DIR)/python"
	python -m pip install -r requirements.txt -t "$(ARTIFACTS_DIR)/python"
